DECLARE
CURSOR EMP_CUR IS SELECT SSN,NAME,SALARY,DEPTNO FROM EMPLOYEE_DETAIL;
EMP_REC EMPLOYEE_DETAIL%ROWTYPE;
BEGIN
OPEN EMP_CUR;
LOOP
FETCH EMP_CUR INTO EMP_REC;
EXIT WHEN EMP_CUR%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('SSN: '||EMP_REC.SSN||' NAME: '||EMP_REC.NAME||' SALARY: '||EMP_REC.SALARY||' DEPTNO: '||EMP_REC.DEPTNO);
END LOOP;
CLOSE EMP_CUR;
END;
/
